name: Update Profile README
on:
  schedule:
    - cron: '0 */24 * * *' # Runs every 24 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://inknowhere.wordpress.com/feed/"
          max_post_count: 5
          readme_path: ./README.md
          template: |
            <!-- BLOG-POST-LIST:START -->
            $newline
            $post_list
            $newline
            <!-- BLOG-POST-LIST:END -->