name: Update Profile README
on:
  schedule:
    - cron: '0 */24 * * *' # Runs every 24 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://inknowhere.wordpress.com/feed/"
          max_post_count: 6
          readme_path: ./README.md
          template: '<td width="50%"><a href="$url"><img width="200px" src="$thumbnail" /></a><br/><a href="$url">$title</a></td>'
          item_exec: "if (post.thumbnail.slice(0, 4) != 'http'){ post.thumbnail = 'https://inknowhere.files.wordpress.com/2018/04/cropped-ink-redible1-1.png'}"
          custom_tags: "thumbnail/media:thumbnail/@url"